# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2
    - name: Set up JDK 15.0.1
      uses: actions/setup-java@v1
      with:
        java-version: 15.0.1

    - name: Run liveproject tests
      run: mvn -Dtest=nextlevel.liveproject.tests.GoogleSearchTest test

    - name: Allure Report with history
      uses: simple-elf/allure-report-action@v1.3
      with:
        allure_results: target/allure-results

