# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Live Project Tests on Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Native Selenium Grid
      run: docker-compose -f docker-compose_native.yml up --scale chrome=4 --remove-orphans -d
    - name: Set up JDK 15
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 15
    - name: Check running containers
      run: docker ps
    - name: Run liveproject tests
      run: mvn -P=liveproject test  
    - name: Get Allure Report history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages
          path: gh-pages
    - name: Generate Allure Report with history
      uses: simple-elf/allure-report-action@v1.3
      if: always()
      id: allure-report
      with:
        allure_results: target/allure-results.
        allure_report: allure-report
        allure_version: 2.13.6
        gh_pages: gh-pages
        allure_history: allure-history
        subfolder: allure
        github_run_num: ${{ github.run_number }}
        github_run_id: ${{ github.run_id }}
        github_repo: ${{ github.repository }}
        github_repo_owner: ${{ github.repository_owner }}
    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: allure-history
