# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI Live Project Tests on Ubuntu

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 15
    - name: Set up Native Selenium Grid with one hub and four Chrome nodes 
      run: docker-compose -f src/main/resources/docker-compose_native.yml up --scale chrome=4 --remove-orphans -d
    - name: Check running containers
      run: docker ps
    - name: Run liveproject tests - Chrome Headless
      run: mvn -P=liveproject test
    - name: Remove the containers
      run: docker-compose -f src/main/resources/docker-compose_native.yml down --remove-orphans
    - name: Set up Native Selenium Grid with one hub and four Firefox nodes 
      run: docker-compose -f src/main/resources/docker-compose_native.yml up --scale firefox=4 --remove-orphans -d
    - name: Check running containers
      run: docker ps
    - name: Run liveproject tests - Firefox Headless
      run: mvn -P=liveproject test
